---
# tasks file for jenkins
- name: Import Jenkins GPG key
  rpm_key:
    state: present
    key: http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key
- name: Add Jenkins repository
  yum_repository:
    name: jenkins
    description: jenkins repository
    baseurl: http://pkg.jenkins.io/redhat
    enabled: yes # 책에서는 아마존 yum 저장소에서 다운로드하려고 no라고 지정하라고 했지만, 안되는 관계로 yes
    gpgcheck: yes
- name: Install Jenkins
  yum:
    name: jenkins
    enablerepo: jenkins
    state: present
- name: Start Jenkins
  service:
    name: jenkins
    enabled: yes
    state: started
